### ISSUE TITLE
Broken Attachments

### ISSUE THREAD

**Issue by networkwithoutborders** [Surveillance-NWB/Smart-Home-Surveillance#15]
@adityamukherjee42 Kindly add the missing/broken attachments in your PR #11 .

**Comment by adityamukherjee42** [comment]
The file is working in my computer , can you mention the error message

**Comment by networkwithoutborders** [comment]
![image](https://user-images.githubusercontent.com/87760470/150830731-9f3d8894-b8fb-4389-8380-827e1ab51ff4.png)
Hi, this is what is observed.  Can you please doublecheck?

**Comment by adityamukherjee42** [comment]
I think the issue is with the path, I have added new gifs once that PR is accepted I will edit the readme and add the new paths relative to this repo

**Comment by networkwithoutborders** [comment]
Done.
