### ISSUE TITLE
Readme conflicts

### ISSUE THREAD

**Issue by networkwithoutborders** [Surveillance-NWB/Smart-Home-Surveillance#5]
@adityamukherjee42 We notice that the readme for the modules you have developed has overlapped with the readme of the repository. Kindly do the neeful at the earliest!

**Comment by adityamukherjee42** [comment]
Yes, I have rectified it

**Comment by networkwithoutborders** [comment]
Thank you for your immediate actions! Please note that any modifications to the repository must be raised via a PR, we will review and merge it then and there.  Hereafter, kindly ensure that other changes are not reverted by the modifications.
