### ISSUE TITLE
File Conflicts

### ISSUE THREAD

**Issue by networkwithoutborders** [Surveillance-NWB/Smart-Home-Surveillance#8]
@Akash-Ramjyothi We are sorry to inform that the commits you made regarding the resolving conflicts have reverted due to technical issues.  We hope you can redo them, please take your time.

**Comment by Akash-Ramjyothi** [comment]
@Surveillance-NWB @Kavyapriyakp Please review, I have resolved the commit.

**Comment by networkwithoutborders** [comment]
Appreciate the efforts! There are readme conflicts again from the PR #1 .  Kindly resolve them.  
Please note that commits to the original readme are expected to be reviewed and merged by the admin.  You can always raise a PR for the same.
