### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by networkwithoutborders** [Surveillance-NWB/Smart-Home-Surveillance#9]
A list of modules have been included in the todo section of readme.  Kindly choose one and work on it.  Acknowledge by commenting the a feasible deadline of the modules and the one you choose to avoid duplication of work.  Do raise PRs as per our documentation style.  All the best!

@Akash-Ramjyothi @adityamukherjee42

**Comment by Akash-Ramjyothi** [comment]
I would like to work on the Emotion recognition module. My proposed Deadline is 10 days from the 1st day of joining on-campus.

**Comment by adityamukherjee42** [comment]
I would like to work on the moule : Log generation with time stamp on entry of known individual (Improvement of face detection module)

My proposed deadline would be 10 days from today

**Comment by networkwithoutborders** [comment]
@adityamukherjee42  @Akash-Ramjyothi  Thank you for your responses.  We understand that the quoted deadline is too far, given the number of modules at hand.  Please try to make it on or before November 10, 2021.  Kindly note that the modules should be light enough to be processed by a Raspberry Pi.

**Comment by Akash-Ramjyothi** [comment]
@Surveillance-NWB I do understand the time constraints. But just now our CT 2 ended, and we have our CT 3 at 8th. Also Diwali is near too. I would also like to start off my work at your office on-campus.
